import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";

import React from "react";
import AuthProvider from "../components/ui/Providers/AuthProvider";
import ThemeProvider from "../components/ui/Providers/ThemeProvider";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body className={inter.className}>
            <>
              <Header />
              {children} 
              <Footer />{" "}
            </>
          </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
